yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
] 

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path("group/<slug>/", views.group_posts, name="group-posts"),
    path("", views.index, name="index"),
    path('profile/<str:username>/', views.profile, name="profile"),
    path('posts/<int:post_id>/', views.post_detail, name="post_detail"),
    path('create/', views.post_create, name="post_create"),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('api/v1/post/<int:id>', views.get_post, name='get_post'),
    path('api/v1/posts/', views.api_posts),
    path('api/v1/posts/<int:id>/', views.api_posts_detail),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api-token-auth/', views.obtain_auth_token),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

'''if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )'''

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
    <body>      
        <footer class="border-top text-center py-3">
            <p>© {{year}} Copyright <span style="color:rgb(255, 0, 0)">Ya</span>tube</p> 
        </footer>
    </body>
</html>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}  
          <li class="nav-item">              
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
              href="{% url 'about:author' %}"> Об авторе
            </a>
          </li>
        {% endwith %}
        {% with request.resolver_match.view_name as view_name %}  
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
        href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% endwith %}
          {% if user.is_authenticated %}
          {% with request.resolver_match.view_name as view_name %} 
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'posts:profile' %}active{% endif %}" 
            href="{% url 'posts:profile' username=user %}">Мои посты</a>
          </li>
          {% endwith %}
          {% with request.resolver_match.view_name as view_name %} 
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
            href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          {% endwith %}
          {% with request.resolver_match.view_name as view_name %}  
          <li class="nav-item">              
            <a class="nav-link {% if view_name  == 'users:password_change' %}active{% endif %}" 
              href="{% url 'users:password_change' %}"> Изменить пароль</a>
          </li>
        {% endwith %}
        {% with request.resolver_match.view_name as view_name %}  
          <li class="nav-item">              
            <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" 
              href="{% url 'users:logout' %}"> Выйти</a>
          </li>
        {% endwith %}
          <li>
            Пользователь: {{ user.username }}
          <li>
          {% else %}
          {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item">              
            <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
              href="{% url 'users:login' %}">Войти</a>
          </li>
          {% endwith %}
          {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item">              
            <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" 
              href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endwith %}
          {% endif %}
        </ul>
      </div>
    </nav>      
  </header>