yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
] 

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path("group/<slug>/", views.group_posts, name="group-posts"),
    path("", views.index, name="index"),
    path('profile/<str:username>/', views.profile, name="profile"),
    path('posts/<int:post_id>/', views.post_detail, name="post_detail"),
    path('create/', views.post_create, name="post_create"),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('api/v1/post/<int:id>', views.get_post, name='get_post'),
    path('api/v1/posts/', views.api_posts),
    path('api/v1/posts/<int:id>/', views.api_posts_detail),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api-token-auth/', views.obtain_auth_token),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

'''if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )'''

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        "Название",
        help_text="Введите название группы",
        max_length=200)
    slug = models.SlugField(
        "Ссылка на группу",
        help_text="Укажите ссылку на группу",
        unique=True, max_length=50)
    description = models.TextField(
        "Описание",
        help_text="Введите описание группы")

    def __str__(self):
        return self.title


class Post(models.Model):
    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата комментария',
        auto_now_add=True
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment

MIN_POST_LEN = 30
MIN_COMMENT_LEN = 5


class PostForm(forms.ModelForm):
    """Форма добавления поста."""

    class Meta:
        model = Post
        fields = ('group', 'text', 'image')

    def clean_text(self):
        data = self.cleaned_data["text"]

        if len(data) < MIN_POST_LEN:
            raise forms.ValidationError(
                f"Длинна поста должна быть не менее {MIN_POST_LEN} символов!"
            )

        return data


class CommentForm(forms.ModelForm):
    """Форма добавления комментария."""
    class Meta:
        model = Comment
        fields = ['text']

    def clean_text(self):
        data = self.cleaned_data['text']

        if len(data) < MIN_COMMENT_LEN:
            raise forms.ValidationError(
                f"Длинна комментария должна быть не менее {MIN_COMMENT_LEN} символов!"
            )

        return data

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import PostForm, CommentForm
from .models import Post, Group, User
from .serializers import PostSerializer
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    return render(request, template, {'group': group, 'posts': posts})


def profile(request, username):
    name = get_object_or_404(User, username=username)
    post_filter = name.posts.all()
    paginator = Paginator(post_filter, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'name': name,
        'post_filter': post_filter,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required(login_url="users:login")
def post_create(request):
    """Добавления поста."""
    template = 'posts/create_post.html'
    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
        )
        if form.is_valid():
            text = form.cleaned_data['text']
            group = form.cleaned_data['group']

            instance = form.save(commit=False)
            instance.author_id = request.user.id
            instance.save()

            user_name = request.user.username

            return redirect('posts:profile', user_name)

        return render(request, template, {'form': form})

    form = PostForm()

    return render(request, template, {'form': form})


@login_required(login_url="users:login")
def post_edit(request, post_id):
    """Редактирование поста. Доступно только автору."""

    template = 'posts/create_post.html'

    post = get_object_or_404(Post, pk=post_id)

    # Если редактировать пытается не автор
    if request.user.id != post.author.id:
        return redirect('posts:post_detail', post.pk)

    form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post
        )
    if form.is_valid():
        form.save()

        user_name = request.user.username
        return redirect('posts:profile', user_name)

    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


def get_post(request, id):
    if request.method == 'GET':
        post = get_object_or_404(Post, pk=id)
        serializer = PostSerializer(post)
        return JsonResponse(serializer.data)


@api_view(['GET', 'POST'])
def api_posts(request):
    if request.method == 'POST':
        serializer = PostSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    posts = Post.objects.all()
    serializer = PostSerializer(posts, many=True)
    return Response(serializer.data)


@api_view(['GET', 'PUT', 'PATCH', 'DELETE'])
def api_posts_detail(request, id):
    post = Post.objects.get(id=id)
    if request.method == 'PUT' or request.method == 'PATCH':
        serializer = PostSerializer(post, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        post.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    serializer = PostSerializer(post)
    return Response(serializer.data)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}
          </div>
          <div class="card-body">  

            {% if form.errors %}
              {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
            {% endif %}

            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}

              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} Записи сообщества {{ group.title }}{% endblock %}
{% block header %} Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  <h2> {{ group.title }} </h2>
    <p> {{ group.description }} </p>

  {% for post in posts %}
      <h3>Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}</h3>
    {% thumbnail post.image "2000x2000" crop="center" upscale=False as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

    {% for post in page_obj %}
    <h3>
        Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    {% thumbnail post.image "2000x2000" crop="center" upscale=False as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}

{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block header %}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d M Y" }}
        </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}
              <br>
              <a href="{% url 'posts:group-posts' post.group.slug %}">
                все записи группы {{ post.group }}
              </a>
            </li>
          {%endif%}
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
          <li class="list-group-item">
            <a href="../../profile/{{ post.author }}/">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "2000x2000" crop="center" upscale=False as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    <p>
      {{ post.text }}
    </p>
      {% if user.id ==  post.author.id %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      {% endif %}
    </article>
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ name.get_full_name }}{% endblock %}
{% block header %}{% endblock %}
{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ name }}</h1>
        <h3>Всего постов: {{ name.posts.count }} </h3>   
        {% for post in page_obj %}
        <article>
          <ul>
          <li>Автор: {{ name.get_full_name }}</li>
          <li>Дата публикации: {{ post.pub_date|date:"d M Y" }}</li>
          </ul>
          {% thumbnail post.image "2000x2000" crop="center" upscale=False as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text|linebreaksbr }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a> 
        </article>
        {% if post.group %}
            <p><a href="{% url 'posts:group-posts' post.group.slug %}">все записи группы {{post.group.slug}}</a></p>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}     
        {% include 'posts/includes/paginator.html' %} 
      </div>
{% endblock %}